# Generated by Django 6.0.3 on 2026-04-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_utilisateur_managers'),
        ('app', '0002_alter_utilisateur_managers_alter_machine_etat_and_more'),
    ]

    operations = [
    ]
