# Generated by Django 6.0.3 on 2026-04-29 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pole_alter_composant_options_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rapportintervention',
            options={},
        ),
        migrations.AlterField(
            model_name='composant',
            name='capacite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='composant',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composants', to='app.machine'),
        ),
        migrations.AlterField(
            model_name='composant',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='composant',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='date_acquisition',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'acquisition"),
        ),
        migrations.AlterField(
            model_name='machine',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_gerees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machine',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Numéro de série'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='qr_code_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(blank=True, choices=[('PC', 'PC'), ('SERVEUR', 'Serveur'), ('IMPRIMANTE', 'Imprimante')], max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='duree',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (minutes)'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='machine_concernee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='app.machine'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='pieces_changees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='redacteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports_rediges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('technician', 'Technician'), ('client', 'Client')], max_length=20, null=True),
        ),
    ]
