# Generated by Django 6.0.3 on 2026-05-05 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_composant_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pole',
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['nom']},
        ),
        migrations.RemoveField(
            model_name='composant',
            name='capacite',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='qr_code_path',
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='pieces_changees',
        ),
        migrations.AddField(
            model_name='machine',
            name='pole',
            field=models.CharField(choices=[('INF', 'Informatique'), ('RH', 'Ressources Humaines'), ('PROD', 'Production'), ('MKT', 'Marketing')], default='INF', max_length=50, verbose_name='Pôle'),
        ),
        migrations.AlterField(
            model_name='composant',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='composants', to='app.machine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='date_acquisition',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('FONCTIONNEL', 'Fonctionnel'), ('EN_PANNE', 'En panne'), ('REPARATION', 'Réparation')], default='FONCTIONNEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(blank=True, choices=[('PC', 'PC'), ('SERVEUR', 'Serveur'), ('IMPRIMANTE', 'Imprimante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='duree',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (min)'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='machine_concernee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='app.machine'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='redacteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to=settings.AUTH_USER_MODEL),
        ),
    ]
