# Generated by Django 6.0.5 on 2026-05-13 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_pole_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapportintervention',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='rapportintervention',
            name='date_cloture',
        ),
        migrations.AddField(
            model_name='machine',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée'), ('echec', 'Échec')], default='en_cours', max_length=50),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_assignees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapportintervention',
            name='type',
            field=models.CharField(blank=True, choices=[('maintenance', 'Maintenance'), ('reparation', 'Réparation'), ('installation', 'Installation')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='composant',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composants', to='app.machine'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('technician', 'Technician'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
