# Generated by Django 6.0.5 on 2026-05-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_fix_rapportintervention_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='composant',
            name='etat',
            field=models.CharField(choices=[('OK', 'OK'), ('FAIBLE', 'Faible'), ('HS', 'Hors service')], default='OK', max_length=20),
        ),
    ]
