# Generated by Django 6.0.5 on 2026-05-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_composant_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('FONCTIONNEL', 'Fonctionnel'), ('EN_PANNE', 'En panne'), ('REPARATION', 'Reparation')], default='FONCTIONNEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='pole',
            field=models.CharField(choices=[('INF', 'Informatique'), ('RH', 'Ressources Humaines'), ('PROD', 'Production'), ('MKT', 'Marketing')], default='INF', max_length=50, verbose_name='Pole'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='duree',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duree (min)'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminee'), ('annulee', 'Annulee'), ('echec', 'Echec')], default='en_cours', max_length=50),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='type',
            field=models.CharField(blank=True, choices=[('maintenance', 'Maintenance'), ('reparation', 'Reparation'), ('installation', 'Installation')], max_length=50, null=True),
        ),
    ]
