# Generated by Django 6.0.4 on 2026-04-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('FONCTIONNEL', 'Fonctionnel'), ('EN_PANNE', 'En panne'), ('REPARATION', 'Réparation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='qr_code_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
