# Generated by Django 6.0.3 on 2026-04-29 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_composant_options_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rapportintervention',
            options={},
        ),
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='composant',
            name='capacite',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='composant',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composants', to='app.machine'),
        ),
        migrations.AlterField(
            model_name='composant',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='composant',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='machine',
            name='date_acquisition',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='machine',
            name='enregistre_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_gerees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('FONCTIONNEL', 'Fonctionnel'), ('EN_PANNE', 'En panne'), ('REPARATION', 'Réparation')], default='FONCTIONNEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='machine',
            name='numero_serie',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='qr_code_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('PC', 'PC'), ('SERVEUR', 'Serveur'), ('IMPRIMANTE', 'Imprimante')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='date_cloture',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='duree',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='machine_concernee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='app.machine'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='pieces_changees',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='redacteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_rediges', to=settings.AUTH_USER_MODEL),
        ),
    ]
