# Generated by Django 6.0.3 on 2026-04-29 10:17

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_composant_options_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='composant',
            options={'ordering': ['nom'], 'verbose_name': 'Composant', 'verbose_name_plural': 'Composants'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['nom'], 'verbose_name': 'Machine', 'verbose_name_plural': 'Machines'},
        ),
        migrations.AlterModelOptions(
            name='rapportintervention',
            options={'ordering': ['-date_cloture'], 'verbose_name': "Rapport d'intervention", 'verbose_name_plural': "Rapports d'intervention"},
        ),
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='composant',
            name='capacite',
            field=models.CharField(max_length=50, verbose_name='Capacité'),
        ),
        migrations.AlterField(
            model_name='composant',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composants', to='app.machine', verbose_name='Machine'),
        ),
        migrations.AlterField(
            model_name='composant',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='composant',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='date_acquisition',
            field=models.DateField(verbose_name="Date d'acquisition"),
        ),
        migrations.AlterField(
            model_name='machine',
            name='enregistre_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_gerees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('FONCTIONNEL', 'Fonctionnel'), ('EN_PANNE', 'En panne'), ('REPARATION', 'Réparation')], default='FONCTIONNEL', max_length=20, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='numero_serie',
            field=models.CharField(max_length=100, unique=True, verbose_name='Numéro de série'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='qr_code_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chemin du QR code'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('PC', 'PC'), ('SERVEUR', 'Serveur'), ('IMPRIMANTE', 'Imprimante')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='date_cloture',
            field=models.DateTimeField(verbose_name='Date de clôture'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='duree',
            field=models.PositiveIntegerField(verbose_name='Durée (minutes)'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='machine_concernee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='app.machine', verbose_name='Machine concernée'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='pieces_changees',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Pièces changées'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='redacteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_rediges', to=settings.AUTH_USER_MODEL, verbose_name='Rédacteur'),
        ),
    ]
