# Generated by Django 6.0.5 on 2026-05-11 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_pole_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapportintervention',
            options={'ordering': ['-date_cloture']},
        ),
        migrations.AlterField(
            model_name='composant',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composants', to='app.machine'),
        ),
        migrations.AlterField(
            model_name='rapportintervention',
            name='machine_concernee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='app.machine'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('technician', 'Technician'), ('client', 'Client')], default='client', max_length=20, null=True),
        ),
    ]
