# Generated by Django 6.0.5 on 2026-05-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_rapportintervention_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
    ]
