# Generated by Django 6.0.5 on 2026-05-11 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_utilisateur_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
    ]
