# Generated by Django 6.0.5 on 2026-05-11 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_utilisateur_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportintervention',
            name='machine_concernee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapport_interventions', to='app.machine'),
        ),
        migrations.CreateModel(
            name='RapportD_inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (min)')),
                ('machine_concernee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='app.machine')),
                ('redacteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_inventaire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_cloture'],
            },
        ),
    ]
