# Generated by Django 6.0.5 on 2026-05-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_rapportintervention_machine_concernee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
