# Generated by Django 6.0.5 on 2026-05-12 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_machine_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='composant',
            name='date_installation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='composant',
            name='etat',
            field=models.CharField(choices=[('OK', 'OK'), ('FAIBLE', 'Faible'), ('HS', 'Hors service')], default='OK', max_length=20),
        ),
        migrations.AddField(
            model_name='composant',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='composant',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole', models.CharField(choices=[('INF', 'Informatique'), ('RH', 'Ressources Humaines'), ('PROD', 'Production'), ('MKT', 'Marketing')], default='INF', max_length=50, verbose_name='Pôle')),
                ('date_affectation', models.DateField()),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Retourné')], default='ACTIVE', max_length=20)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='app.machine')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_affectation'],
            },
        ),
    ]
