# Generated by Django 6.0.5 on 2026-05-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_composant_date_installation_composant_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='pole',
            field=models.CharField(choices=[('INF', 'Informatique'), ('RH', 'Ressources Humaines'), ('PROD', 'Production'), ('MKT', 'Marketing'), ('FIN', 'Finance'), ('AUTRE', 'Autre')], default='INF', max_length=50, verbose_name='Pôle'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='pole',
            field=models.CharField(choices=[('INF', 'Informatique'), ('RH', 'Ressources Humaines'), ('PROD', 'Production'), ('MKT', 'Marketing'), ('FIN', 'Finance'), ('AUTRE', 'Autre')], default='INF', max_length=50, verbose_name='Pôle'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('technician', 'Technician')], default='technician', max_length=20, null=True),
        ),
    ]
